# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtOufbY5cnqVnbnVH-qA7S5598AwHk58

# Yeni Bölüm
"""

!pip -q install "transformers>=4.57.0" accelerate pillow

import torch
from transformers import Qwen3VLForConditionalGeneration, AutoProcessor

MODEL_ID = "Qwen/Qwen3-VL-2B-Instruct"

processor = AutoProcessor.from_pretrained(MODEL_ID)

model = Qwen3VLForConditionalGeneration.from_pretrained(
    MODEL_ID,
    dtype=torch.float16,
    device_map="auto"
)

print("Model hazır.")

from google.colab import files
from PIL import Image
from IPython.display import display

uploaded = files.upload()

image_path = next(iter(uploaded))
image = Image.open(image_path).convert("RGB")

display(image)

print("Yüklenen dosya:", image_path)
print("Görüntü boyutu:", image.size)

from google.colab import files
import zipfile
import os

uploaded = files.upload()

zip_name = next(iter(uploaded))

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall("/content")

print("ZIP açıldı.")
print(os.listdir("/content/satdemo"))

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

base_folder = "/content/satdemo"

# CSV'yi oku
pairs = pd.read_csv(
    os.path.join(base_folder, "image_label_pairs.csv"),
    dtype=str
)

# Sadece image ve label'ı birlikte bulunan kayıtları al
pairs = pairs[
    pairs["pair_status"] == "matched"
].reset_index(drop=True)

print("Eşleşen image-label sayısı:", len(pairs))
display(pairs.head())

# İlk satırı seç
row = pairs.iloc[0]

image_path = os.path.join(base_folder, row["image_path"])
label_path = os.path.join(base_folder, row["label_path"])

# Optik görüntüyü aç
image = Image.open(image_path).convert("RGB")
image_array = np.array(image)

# Label maskesini aç
label_array = np.array(Image.open(label_path))

# Label çok kanallıysa ilk kanalı kullan
if label_array.ndim == 3:
    label_array = label_array[:, :, 0]

# Sıfırdan büyük değerleri hedef alan kabul et
binary_mask = label_array > 0

# Görüntü, label ve üst üste bindirilmiş hâli
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

axes[0].imshow(image_array)
axes[0].set_title("Optik görüntü")
axes[0].axis("off")

axes[1].imshow(binary_mask, cmap="gray")
axes[1].set_title("Label maskesi")
axes[1].axis("off")

axes[2].imshow(image_array)
axes[2].imshow(binary_mask, alpha=0.4, cmap="Reds")
axes[2].set_title("Image + label")
axes[2].axis("off")

plt.show()

print("Sample ID:", row["sample_id"])
print("Image:", image_path)
print("Label:", label_path)
print("Label değerleri:", np.unique(label_array))

import os
import numpy as np
import pandas as pd
from PIL import Image

def get_direction_from_mask(label_path):
    mask = np.array(Image.open(label_path))

    if mask.ndim == 3:
        mask = mask[:, :, 0]

    mask = mask > 0

    # Maskede hedef yoksa
    if not mask.any():
        return "unclear"

    y_coords, x_coords = np.where(mask)

    center_x = x_coords.mean() / mask.shape[1]
    center_y = y_coords.mean() / mask.shape[0]

    # Ortadaki alanı center kabul et
    if 0.33 <= center_x <= 0.67 and 0.33 <= center_y <= 0.67:
        return "center"

    horizontal_distance = abs(center_x - 0.5)
    vertical_distance = abs(center_y - 0.5)

    # Baskın ekseni seç
    if horizontal_distance > vertical_distance:
        return "west" if center_x < 0.5 else "east"
    else:
        return "north" if center_y < 0.5 else "south"

results = []

for _, row in pairs.iterrows():
    label_path = os.path.join(base_folder, row["label_path"])

    expected_answer = get_direction_from_mask(label_path)

    results.append({
        "sample_id": row["sample_id"],
        "image_path": row["image_path"],
        "label_path": row["label_path"],
        "expected_answer": expected_answer
    })

samples = pd.DataFrame(results)

display(samples.head(10))
print(samples["expected_answer"].value_counts())

from google.colab import drive

drive.mount("/content/drive")

import os

drive_folder = "/content/drive/MyDrive/__VLM/satdemo"
os.makedirs(drive_folder, exist_ok=True)

import os

folder_path = "/content/drive/MyDrive/___VLM/satdemo"
os.makedirs(folder_path, exist_ok=True)

csv_path = os.path.join(folder_path, "samples.csv")
samples.to_csv(csv_path, index=False)

print("Kaydedildi:", csv_path)
print("Klasör içeriği:", os.listdir(folder_path))

import os

folder_path = "/content/drive/MyDrive/__VLM/satdemo"
os.makedirs(folder_path, exist_ok=True)

csv_path = os.path.join(folder_path, "samples.csv")
samples.to_csv(csv_path, index=False)

print("Kaydedildi:", csv_path)
print("Klasör içeriği:", os.listdir(folder_path))

row = samples.iloc[0]

image_path = os.path.join(
    "/content/satdemo",
    row["image_path"]
)

image = Image.open(image_path).convert("RGB")

display(image)

print("Sample ID:", row["sample_id"])
print("Beklenen yön:", row["expected_answer"])
print("Görüntü yolu:", image_path)

import numpy as np
from PIL import Image
from IPython.display import display

row = pairs.iloc[0]

image_path = os.path.join(base_folder, row["image_path"])
label_path = os.path.join(base_folder, row["label_path"])

image = Image.open(image_path).convert("RGB")
image_array = np.array(image).copy()

label_array = np.array(Image.open(label_path))

if label_array.ndim == 3:
    label_array = label_array[:, :, 0]

mask = label_array > 0

# Hedef alanları yarı saydam kırmızı yap
overlay = image_array.copy()
overlay[mask] = (
    0.5 * overlay[mask] +
    0.5 * np.array([255, 0, 0])
).astype(np.uint8)

overlay_image = Image.fromarray(overlay)

display(overlay_image)

from scipy.ndimage import label

connected_mask, region_count = label(mask)

print("Ayrı işaretli bölge sayısı:", region_count)

import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from scipy.ndimage import label as count_components

def inspect_sample(sample_index):
    row = pairs.iloc[sample_index]

    image_path = os.path.join(base_folder, row["image_path"])
    label_path = os.path.join(base_folder, row["label_path"])

    image = Image.open(image_path).convert("RGB")
    image_array = np.array(image)

    label_array = np.array(Image.open(label_path))

    if label_array.ndim == 3:
        label_array = label_array[:, :, 0]

    mask = label_array > 0

    # Ayrı bölgeleri say
    _, region_count = count_components(mask)

    # Kırmızı overlay oluştur
    overlay = image_array.copy()

    overlay[mask] = (
        0.5 * overlay[mask]
        + 0.5 * np.array([255, 0, 0])
    ).astype(np.uint8)

    overlay_image = Image.fromarray(overlay)

    # 90 derece saat yönünde döndür
    rotated_image = overlay_image.rotate(-90, expand=True)

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(overlay_image)
    axes[0].set_title("Orijinal")
    axes[0].axis("off")

    axes[1].imshow(rotated_image)
    axes[1].set_title("90° döndürülmüş")
    axes[1].axis("off")

    plt.show()

    print("Sample ID:", row["sample_id"])
    print("Doğru bölge sayısı:", region_count)

    return overlay_image, rotated_image, region_count

overlay_image, rotated_image, expected_count = inspect_sample(7)

inspect_sample(15)



"""# Yeni Bölüm"""

import os
import shutil

source_folder = "/content/satdemo"
drive_folder = "/content/drive/MyDrive/__VLM/satdemo"

os.makedirs(drive_folder, exist_ok=True)

if os.path.exists(source_folder):
    shutil.copytree(
        source_folder,
        drive_folder,
        dirs_exist_ok=True
    )
    print("Dataset Drive'a kopyalandı.")
else:
    print("/content/satdemo bulunamadı. ZIP'i yeniden açman gerekiyor.")

print(os.listdir(drive_folder))

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

print("Model var mı:", "model" in globals())
print("Processor var mı:", "processor" in globals())

import torch

def ask_vlm(input_image):
    prompt = """
Look carefully at the image.

How many separate red highlighted regions are visible?

Answer using exactly one of these:
0, 1, 2, 3, 4+
"""

    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": input_image
                },
                {
                    "type": "text",
                    "text": prompt
                }
            ]
        }
    ]

    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt"
    )

    inputs = inputs.to(model.device)

    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=20,
            do_sample=False
        )

    output_ids = generated_ids[:, inputs["input_ids"].shape[1]:]

    answer = processor.batch_decode(
        output_ids,
        skip_special_tokens=True
    )[0]

    return answer.strip()

print("ask_vlm hazır.")

import os
import pandas as pd
import numpy as np
from PIL import Image
from scipy.ndimage import label as count_components
from IPython.display import display

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

pairs = pd.read_csv(
    os.path.join(base_folder, "image_label_pairs.csv"),
    dtype=str
)

pairs = pairs[
    pairs["pair_status"] == "matched"
].reset_index(drop=True)

row = pairs.iloc[0]

image_path = os.path.join(base_folder, row["image_path"])
label_path = os.path.join(base_folder, row["label_path"])

image = Image.open(image_path).convert("RGB")
image_array = np.array(image)

label_array = np.array(Image.open(label_path))

if label_array.ndim == 3:
    label_array = label_array[:, :, 0]

mask = label_array > 0

_, expected_count = count_components(mask)

overlay = image_array.copy()
overlay[mask] = (
    0.5 * overlay[mask]
    + 0.5 * np.array([255, 0, 0])
).astype(np.uint8)

overlay_image = Image.fromarray(overlay)
rotated_image = overlay_image.rotate(-90, expand=True)

display(overlay_image)

print("Doğru bölge sayısı:", expected_count)

model_answer_original = ask_vlm(overlay_image)
model_answer_rotated = ask_vlm(rotated_image)

print("Gerçek cevap:", expected_count)
print("Orijinal görüntü cevabı:", model_answer_original)
print("Döndürülmüş görüntü cevabı:", model_answer_rotated)

import os
import re
import time
import numpy as np
import pandas as pd
from PIL import Image
from scipy.ndimage import label as count_components
from IPython.display import display

def normalize_answer(answer):
    """
    Model cevabını şu sınıflardan birine dönüştürür:
    0, 1, 2, 3, 4+
    """
    text = str(answer).strip().lower()

    if "4+" in text or "4 +" in text:
        return "4+"

    numbers = re.findall(r"\d+", text)

    if not numbers:
        return "unknown"

    number = int(numbers[0])

    if number >= 4:
        return "4+"

    return str(number)

def prepare_sample(row, base_folder):
    image_path = os.path.join(base_folder, row["image_path"])
    label_path = os.path.join(base_folder, row["label_path"])

    image = Image.open(image_path).convert("RGB")
    image_array = np.array(image)

    label_array = np.array(Image.open(label_path))

    if label_array.ndim == 3:
        label_array = label_array[:, :, 0]

    mask = label_array > 0

    _, region_count = count_components(mask)

    expected_answer = "4+" if region_count >= 4 else str(region_count)

    overlay = image_array.copy()

    overlay[mask] = (
        0.5 * overlay[mask]
        + 0.5 * np.array([255, 0, 0])
    ).astype(np.uint8)

    overlay_image = Image.fromarray(overlay)

    rotated_image = overlay_image.rotate(
        -90,
        expand=True
    )

    return overlay_image, rotated_image, region_count, expected_answer

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

results_path = os.path.join(
    base_folder,
    "results.csv"
)

results = []

for index, row in pairs.iterrows():
    sample_id = row["sample_id"]

    print(
        f"\nÖrnek {index + 1}/{len(pairs)} "
        f"- Sample ID: {sample_id}"
    )

    try:
        (
            overlay_image,
            rotated_image,
            region_count,
            expected_answer
        ) = prepare_sample(
            row,
            base_folder
        )

        original_raw = ask_vlm(overlay_image)
        original_answer = normalize_answer(original_raw)

        rotated_raw = ask_vlm(rotated_image)
        rotated_answer = normalize_answer(rotated_raw)

        original_correct = (
            original_answer == expected_answer
        )

        rotated_correct = (
            rotated_answer == expected_answer
        )

        rotation_consistent = (
            original_answer == rotated_answer
        )

        results.append({
            "sample_id": sample_id,
            "region_count": region_count,
            "expected_answer": expected_answer,
            "original_raw_answer": original_raw,
            "original_answer": original_answer,
            "rotated_raw_answer": rotated_raw,
            "rotated_answer": rotated_answer,
            "original_correct": original_correct,
            "rotated_correct": rotated_correct,
            "rotation_consistent": rotation_consistent,
            "status": "success"
        })

        print("Gerçek cevap:", expected_answer)
        print("Orijinal cevap:", original_answer)
        print("Döndürülmüş cevap:", rotated_answer)
        print("Orijinal doğru mu?:", original_correct)
        print("Döndürülmüş doğru mu?:", rotated_correct)
        print("Tutarlı mı?:", rotation_consistent)

    except Exception as error:
        print("Hata:", error)

        results.append({
            "sample_id": sample_id,
            "region_count": "",
            "expected_answer": "",
            "original_raw_answer": "",
            "original_answer": "",
            "rotated_raw_answer": "",
            "rotated_answer": "",
            "original_correct": False,
            "rotated_correct": False,
            "rotation_consistent": False,
            "status": f"error: {error}"
        })

    # Her örnekten sonra Drive'a kaydet
    results_df = pd.DataFrame(results)
    results_df.to_csv(
        results_path,
        index=False
    )

    print("Ara sonuç kaydedildi:", results_path)

print("\nDeney tamamlandı.")

results_df = pd.read_csv(results_path)

successful = results_df[
    results_df["status"] == "success"
].copy()

original_accuracy = successful[
    "original_correct"
].mean()

rotated_accuracy = successful[
    "rotated_correct"
].mean()

rotation_consistency = successful[
    "rotation_consistent"
].mean()

print("Başarılı örnek sayısı:", len(successful))

print(
    "Orijinal doğruluk:",
    round(original_accuracy * 100, 2),
    "%"
)

print(
    "Döndürülmüş doğruluk:",
    round(rotated_accuracy * 100, 2),
    "%"
)

print(
    "Rotation consistency:",
    round(rotation_consistency * 100, 2),
    "%"
)

display(results_df.head())

import pandas as pd

results_path = "/content/drive/MyDrive/__VLM/satdemo/results.csv"

results_df = pd.read_csv(results_path)

successful = results_df[
    results_df["status"] == "success"
].copy()

# True/False sütunlarını güvenli biçimde boolean'a çevir
bool_columns = [
    "original_correct",
    "rotated_correct",
    "rotation_consistent"
]

for column in bool_columns:
    successful[column] = (
        successful[column]
        .astype(str)
        .str.lower()
        .map({"true": True, "false": False})
    )

original_accuracy = successful["original_correct"].mean()
rotated_accuracy = successful["rotated_correct"].mean()
rotation_consistency = successful["rotation_consistent"].mean()

print("Başarılı örnek sayısı:", len(successful))
print("Orijinal doğruluk:", round(original_accuracy * 100, 2), "%")
print("Döndürülmüş doğruluk:", round(rotated_accuracy * 100, 2), "%")
print("Rotation consistency:", round(rotation_consistency * 100, 2), "%")

display(results_df.head())

class_summary = successful.groupby("expected_answer").agg(
    sample_count=("sample_id", "count"),
    original_accuracy=("original_correct", "mean"),
    rotated_accuracy=("rotated_correct", "mean"),
    rotation_consistency=("rotation_consistent", "mean")
).reset_index()

class_summary["original_accuracy"] *= 100
class_summary["rotated_accuracy"] *= 100
class_summary["rotation_consistency"] *= 100

display(class_summary.round(2))

pd.crosstab(
    successful["expected_answer"],
    successful["original_answer"],
    rownames=["Gerçek cevap"],
    colnames=["Model cevabı"]
)

"""# Yeni Bölüm"""



import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

# CSV'yi oku
pairs = pd.read_csv(
    os.path.join(base_folder, "image_label_pairs.csv"),
    dtype=str
)

# Sadece image ve label'ı birlikte bulunan kayıtları al
pairs = pairs[
    pairs["pair_status"] == "matched"
].reset_index(drop=True)

print("Eşleşen image-label sayısı:", len(pairs))
display(pairs.head())

import os
from PIL import Image
from IPython.display import display

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

sample_id = "000000000000"

image_path = os.path.join(
    base_folder,
    "images",
    f"{sample_id}.tif"
)

image = Image.open(image_path).convert("RGB")

display(image)
print("Görüntü yolu:", image_path)

import pandas as pd
import os

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

image_labels_path = os.path.join(
    base_folder,
    "image_label_pairs.csv"
)

image_labels = pd.read_csv(
    image_labels_path,
    dtype={"sample_id": str}
)

image_labels["sample_id"] = (
    image_labels["sample_id"]
    .astype(str)
    .str.zfill(12)
)

display(image_labels.head())

import pandas as pd
import os

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

pairs_path = os.path.join(
    base_folder,
    "image_label_pairs.csv"
)

pairs = pd.read_csv(
    pairs_path,
    dtype={"sample_id": str}
)

pairs["sample_id"] = (
    pairs["sample_id"]
    .astype(str)
    .str.zfill(12)
)

# Yeni hasar etiketi sütunu
pairs["image_damage_label"] = ""

output_path = os.path.join(
    base_folder,
    "image_damage_labels.csv"
)

pairs[
    ["sample_id", "image_filename", "image_damage_label"]
].to_csv(
    output_path,
    index=False
)

print("Oluşturuldu:", output_path)
display(
    pairs[
        ["sample_id", "image_filename", "image_damage_label"]
    ].head()
)

import os
import numpy as np
from PIL import Image
import pandas as pd

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

pairs = pd.read_csv(
    os.path.join(base_folder, "image_label_pairs.csv"),
    dtype={"sample_id": str}
)

pairs = pairs[pairs["pair_status"] == "matched"].reset_index(drop=True)

for i in range(min(10, len(pairs))):
    row = pairs.iloc[i]

    label_path = os.path.join(
        base_folder,
        row["label_path"]
    )

    label_array = np.array(Image.open(label_path))

    print(
        row["sample_id"],
        "benzersiz label değerleri:",
        np.unique(label_array)
    )

import os
import numpy as np
import pandas as pd
from PIL import Image

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

pairs = pd.read_csv(
    os.path.join(base_folder, "image_label_pairs.csv"),
    dtype={"sample_id": str}
)

pairs = pairs[pairs["pair_status"] == "matched"].reset_index(drop=True)

rows = []

for _, row in pairs.iterrows():
    label_path = os.path.join(
        base_folder,
        row["label_path"]
    )

    label_array = np.array(Image.open(label_path))

    unique_values = np.unique(label_array)
    damage_values = unique_values[unique_values != 0]

    rows.append({
        "sample_id": row["sample_id"],
        "label_values": ",".join(map(str, damage_values))
    })

label_classes_df = pd.DataFrame(rows)

display(label_classes_df)
print(label_classes_df["label_values"].value_counts())

import os
import numpy as np
import pandas as pd
from PIL import Image

base_folder = "/content/drive/MyDrive/__VLM/satdemo"

pairs = pd.read_csv(
    os.path.join(base_folder, "image_label_pairs.csv"),
    dtype={"sample_id": str}
)

pairs = pairs[
    pairs["pair_status"] == "matched"
].reset_index(drop=True)

rows = []

for _, row in pairs.iterrows():
    label_path = os.path.join(
        base_folder,
        row["label_path"]
    )

    label_array = np.array(
        Image.open(label_path)
    )

    if label_array.ndim == 3:
        label_array = label_array[:, :, 0]

    damage_values = np.unique(label_array)
    damage_values = damage_values[
        damage_values != 0
    ]

    if len(damage_values) == 0:
        patch_class = 0
    else:
        # Aynı patch içinde 3 ve 4 varsa 4 seçilir
        patch_class = int(damage_values.max())

    rows.append({
        "sample_id": str(row["sample_id"]).zfill(12),
        "image_path": row["image_path"],
        "label_path": row["label_path"],
        "image_class_id": patch_class,
        "image_damage_label": f"class_{patch_class}"
    })

image_damage_df = pd.DataFrame(rows)

display(image_damage_df.head())

print(
    image_damage_df[
        "image_damage_label"
    ].value_counts()
)

image_damage_path = os.path.join(
    base_folder,
    "image_damage_labels.csv"
)

image_damage_df.to_csv(
    image_damage_path,
    index=False
)

print("Kaydedildi:", image_damage_path)

pilot_class_3 = image_damage_df[
    image_damage_df["image_class_id"] == 3
].sample(
    n=8,
    random_state=42
)

pilot_class_4 = image_damage_df[
    image_damage_df["image_class_id"] == 4
].sample(
    n=8,
    random_state=42
)

pilot_images = pd.concat(
    [pilot_class_3, pilot_class_4],
    ignore_index=True
).sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

display(pilot_images)

print(
    pilot_images[
        "image_damage_label"
    ].value_counts()
)

!pip -q install datasets

from datasets import load_dataset
import pandas as pd

geonlp = load_dataset(
    "FatmaElik/turkish-disaster-news-geonlp"
)

news_parts = []

for split_name in geonlp.keys():
    split_df = geonlp[
        split_name
    ].to_pandas()

    split_df["split"] = split_name
    news_parts.append(split_df)

news_df = pd.concat(
    news_parts,
    ignore_index=True
)

print("Toplam haber:", len(news_df))
print("Sütunlar:")
print(news_df.columns.tolist())

display(news_df.head())

print("GeoNLP damage_level değerleri:")

print(
    news_df["damage_level"]
    .astype(str)
    .str.strip()
    .str.lower()
    .value_counts(dropna=False)
)



